SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USUARIOS] (
		[ID]        [int] NOT NULL,
		[nome]      [nchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
		[senha]     [nchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
		CONSTRAINT [PK_USUARIOS]
		PRIMARY KEY
		CLUSTERED
		([ID])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] SET (LOCK_ESCALATION = TABLE)
GO
